name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests before deployment (currently disabled)'
        required: false
        type: boolean
        default: false
      enable_deployment:
        description: 'Enable deployment to Azure (currently disabled)'
        required: false
        type: boolean
        default: false

jobs:
  test:
    # Only run tests on manual trigger without skip_tests
    if: github.repository == 'nishantuzir/agentic-alliance' && github.event_name == 'workflow_dispatch' && !github.event.inputs.skip_tests
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: [test]
    # Only run build with tests on manual trigger without skip_tests
    if: github.repository == 'nishantuzir/agentic-alliance' && github.event_name == 'workflow_dispatch' && !github.event.inputs.skip_tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push agent-service container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/agentic-alliance.service:${{ github.sha }}
          file: docker/Dockerfile.service

  build-skip-tests:
    runs-on: ubuntu-latest
    # Run on push to main or manual trigger with skip_tests
    if: github.repository == 'nishantuzir/agentic-alliance' && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.skip_tests))
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push agent-service container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/agentic-alliance.service:${{ github.sha }}
          file: docker/Dockerfile.service

  # Deployment job is commented out but can be enabled later
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build, build-skip-tests]
  #   if: github.repository == 'nishantuzir/agentic-alliance' && (github.event_name == 'workflow_dispatch' && github.event.inputs.enable_deployment)
  #   steps:
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'agent-service'
  #         slot-name: 'production'
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/agentic-alliance.service:${{ github.sha }}'
